AllCops:
  Excludes:
    - bin/**
    - config/unicorn.rb
    - db/schema.rb
  RunRailsCops: true

Metrics/LineLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false
